apiVersion: apps/v1
kind: Deployment
metadata:
  name: olivaclient-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: olivaclient
  template:
    metadata:
      labels:
        app: olivaclient
    spec:
      containers:
      - name: olivaclient
        image: olivaclient:latest
        ports:
        - containerPort: 80
